calculator
tilacyn/practiceJava pull request #15
Opened 2017-11-29 13:22 UTC by tilacyn

2017-12-09 15:02 UTC, jzuken requested changes

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/stack/Stack.java
> +            return null;
лучше исключение бросить при пустом стеке

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    public Calculator(String infixSequence) {
аннотации?

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    Calculator(String infixSequence, Stack operations, Stack numbers) {
а в чём смысл того, что он не паблик?

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +     * @param infixSequence
а где описания?
-0.5

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +        index--;
а это тут зачем делается? никто же результат декремента не увидит

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +            return true;
это очень некрасивая запись, не надо так писать. я говорил, что за неё баллы сильно снимать буду: строчка 14 [тут](https://docs.google.com/spreadsheets/d/1hRcQk4FmwK0mZYWKbvjGx-ypwqxcNjtXlRab-WDj7Ek/edit#gid=0).
-2

2017-12-09 15:02 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
а оно зачем пакетного уровня?

2017-12-16 10:32 UTC, tilacyn commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
Потому что и этот метод, и конструктор от стеков используются и должны использоваться только в тестах

2017-12-16 12:43 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
кто это сказал?

2017-12-16 14:06 UTC, tilacyn commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
Ну можно конструктор сделать public, но метод getPolishSequence то зачем?

2017-12-16 14:52 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
ну вот и я думаю, что никому его не надо показывать

2017-12-16 14:57 UTC, tilacyn commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
Просто я с помощью него метод тестирую, поэтому он package-private

2017-12-17 06:48 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
ладно, getPolishSequence() не такой уж бесполезный, чтобы показывать его внутри пакета, а вот конструктор надо открыть

2017-12-17 08:47 UTC, tilacyn commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    ArrayList<Integer> getPolishSequence() {
Хорошо, исправил

2017-12-24 07:22 UTC, jzuken requested changes

2017-12-24 07:22 UTC, jzuken commented on Calculator/build.gradle
> +dependencies {
пакет с аннотациями!!

2017-12-24 07:22 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/stack/Stack.java
> +        array[size] = elem;
ну а если оно за границы внутреннего массива выйдет?

2017-12-24 07:22 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/stack/Stack.java
> +        return array[size];
и тут аналогично, тут надо исключение кидать
-1

2017-12-24 07:22 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +    public Calculator(@NotNull String infixSequence, @NotNull Stack operations, @NotNull Stack numbers) {
параметры-типы генериков потерялись
-0.5

2017-12-24 07:22 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +     * @param n
я вас не заставляю писать джавадоки к приватным методам, но если пишете, так пишите уж хорошо

2017-12-24 07:22 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +            if (current == -1) {
а зачем так запутывать код? почему бы просто не вычитывать символы операций тут?

2017-12-25 14:06 UTC, tilacyn commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +            if (current == -1) {
Можете еще раз объяснить, что вы предлагаете? Если вы про то, что в polishSequence лежат инты, то так удобно, ведь все числа, которые больше нуля - это числа(операнды), а которые меньше нуля - это операции, по-моему так лучше, чем парсить чары.

2017-12-26 04:40 UTC, jzuken commented on Calculator/src/main/java/ru/tilacyn/calculator/Calculator.java
> +            if (current == -1) {
может вам так и удобнее, но код от этого сильно страдает. в принципе, можно было бы завести константы с подобными отрицательными значениями, и использовать тут их, будет более читаемо

2017-12-26 11:05 UTC, merged