Reflector
tilacyn/practiceJava pull request #22
Opened 2017-12-21 20:43 UTC by tilacyn

2017-12-27 18:13 UTC, jzuken requested changes

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +                result += '.';
конкатенация строк в цикле это дело такое. для этого есть StringBuilder. а вообще есть String.replaceAll()

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +     * @return
комментарий пропал
-0.5

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        for (; i < s.length() && s.charAt(i) != ' '; i++) {
это тоже жесть какая-то. найти пробел в строке можно просто поиском по строке. у String много разных полезных методов есть

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +            if (method.getReturnType().getName() == "void") {
писал вроде про это уже. строки -- объекты, их нельзя сравнивать через равенство
-1

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        Runtime.getRuntime().exec("find . -maxdepth 1 -name \"*class\" | xargs rm").waitFor();
эээ, это что? а если у меня нет этой команды (например, под виндами её нет по дефолту)?

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        Runtime.getRuntime().exec("javac SomeClass.java").waitFor();
не надо так, лучше возьмите какой-нибудь вариант ClassLoader'а и загрузите файл в него

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        HashSet<String> secondMethods = new HashSet();
угловые скобки потерялись справа
-0.5

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +     * @param first
и снова комменты провисли
-0.5

2017-12-27 18:13 UTC, jzuken commented on Reflector/src/test/java/ru/tilacyn/reflector/ReflectorTest.java
> +        if (length > Integer.MAX_VALUE) {
то что?

2017-12-28 08:11 UTC, tilacyn commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        Runtime.getRuntime().exec("javac SomeClass.java").waitFor();
Но сначала ведь скомпилировать надо

2017-12-29 13:03 UTC, jzuken commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        Runtime.getRuntime().exec("javac SomeClass.java").waitFor();
ну какой-нибудь URLClassLoader умеет сорцы подгружать и потом инстанцировать классы

2018-01-15 11:05 UTC, tilacyn commented on Reflector/src/main/java/ru/tilacyn/reflector/Reflector.java
> +        Runtime.getRuntime().exec("javac SomeClass.java").waitFor();
Я попытался разобраться, и вроде URLClassLoader не умеет компилировать или эта проблема вообще не решается в несколько строк?

2018-01-27 08:16 UTC, merged