ZipFile
tilacyn/practiceJava pull request #24
Opened 2017-12-26 20:07 UTC by tilacyn

2017-12-29 12:57 UTC, jzuken requested changes

2017-12-29 12:57 UTC, jzuken commented on ZipFile/TestZip/4/4.txt
> +4
если это тестовые файлы, то их надо положить в src/java/test/resources, а если генерящиеся -- то удалить из гита

2017-12-29 12:57 UTC, jzuken commented on ZipFile/src/main/java/ru/tilacyn/zipfile/ZipUtilConsole.java
> +     * @throws IOException
и снова недописанная документация. время идёт, а ничего не меняется
-0.5

2018-01-08 15:20 UTC, jzuken commented
эмм, а где файлы проекта и gradle?

2018-01-08 15:30 UTC, tilacyn commented
Но ведь они же тут Сейчас в ветке zipfile лежат файлы ZipUtilConsole.java, ZipUtilConsoleTest.java, build.gradle и тестовые в нужной директории -- Максим Крючков, 2 курс, АУ08.01.2018, 18:20, "Timofey Bryksin" <notifications@github.com>:эмм, а где файлы проекта и gradle?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

2018-01-14 12:21 UTC, closed without merging