TF
tilacyn/practiceJava pull request #28
Opened 2018-02-09 20:20 UTC by tilacyn

2018-02-11 12:41 UTC, jzuken requested changes

2018-02-11 12:41 UTC, jzuken commented on MyTemporaryFolder/src/test/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolderTest.java
> +public class MyTemporaryFolderTest {
все тесты кроме noParamsConstructor() валятся с IOException:

java.io.IOException: Системе не удается найти указанный путь

	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at ru.tilacyn.myTemporaryFolder.MyTemporaryFolder.create(MyTemporaryFolder.java:43)
	at ru.tilacyn.myTemporaryFolder.MyTemporaryFolderTest.create(MyTemporaryFolderTest.java:20)

возможно потому, что вы пытаетесь создавать файлы в несуществующих директориях

2018-02-11 12:41 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +        tmpFolder.mkdir();
создали файл, удалили, потом создали каталог. почему оно так?
а ещё, кстати, эти методы что-то возвращают полезное о результате своей работы

2018-02-11 12:41 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +     * @param fileName specified file name
а тут описания методов куда-то пропали
-1

2018-02-11 12:41 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +     * @param paths path to folder
ну неправда, там массив же передаётся

2018-02-11 15:28 UTC, tilacyn commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +        tmpFolder.mkdir();
Потому что createTempFile - это простой способ создать файл с рандомным названием в указанной директории. Поэтому если вызвать delete, а потом mkdir, то создастся директория с рандомным названием, а не файл. Конкретно в методе create это используется, потому что в функциональности TF есть опция создать ее в дефолтном месте. А для этого нужно просто передать null в качестве последнего параметра в метод createTempFile

2018-02-11 15:45 UTC, tilacyn commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +     * @param fileName specified file name
Просто я делал документацию, примерно такую же как и в исходниках

2018-02-12 07:01 UTC, jzuken commented
у меня после прохода всех тестов осталась на диске папка src/test/resources, что не совсем как ожидаемое поведение вроде

2018-02-12 07:03 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +        tmpFolder.mkdir();
вот это чем не устраивает?
https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempDirectory(java.nio.file.Path,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...)

2018-02-12 07:04 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +        tmpFolder.mkdir();
я даже не поленился и нашёл статью на stackoverflow, из которой вы этот пример взяли. но там же ниже приводятся и гораздо более адекватные решения

2018-02-12 07:08 UTC, jzuken requested changes

2018-02-12 07:08 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +public class MyTemporaryFolder extends ExternalResource {
это нормально, что нигде не используется аннотация Rule?

2018-02-12 07:10 UTC, jzuken requested changes

2018-02-12 07:10 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +            throw new IOException();
и что узнает пользователь об этой исключительной ситуации, поймав такое исключение? правильно, ничего. раз уж вы сами кидаете исключение, нужно добавлять в них хоть какую-то полезную информацию либо в имени самого исключения, либо текстовым параметром

2018-02-13 18:09 UTC, jzuken requested changes

2018-02-13 18:09 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +    public void before() throws IOException {
оно вроде бы ничего не бросает

2018-02-13 18:09 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
>      public File newFile(@NotNull String fileName) throws IOException {
ну а здесь чем createTempFile() не угодил7

2018-02-13 18:09 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +    public File newFolder(@NotNull String... paths) throws Exception {
и зачем тут Exception?

2018-02-13 18:09 UTC, jzuken commented on MyTemporaryFolder/src/main/java/ru/tilacyn/myTemporaryFolder/MyTemporaryFolder.java
> +    public File newFolder(@NotNull String... paths) throws Exception {
и вообще где документирование бросаемых исключения? у вас и так впритык баллов уже, снимать больше некуда, а вы одни и те же ошибки допускаете. я уже который раз об этом пишу.

2018-02-14 16:54 UTC, merged