Dijkstra
tilacyn/practiceJava pull request #29
Opened 2018-02-11 15:11 UTC by tilacyn

2018-02-12 07:44 UTC, jzuken requested changes

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/main/Main.java
> +        int n = in.nextInt();
классика жанра -- приложение стартует, показывает чёрный экран и чего-то ждёт, а пользователь должен сидеть и гадать. сделайте, пожалуйста, ввод значений из файла и приложите файл, на котором всё работает. или вы каждый раз это всё вводите руками?
-1

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/test/java/ru/tilacyn/graph/GraphTest.java
> +        public static <T> ArrayList<T> arrayToAL(T[] array) {
лучше использовать `new ArrayList<>(Arrays.asList(array))`, не надо велосипеды городить. а в java 9 даже есть https://docs.oracle.com/javase/9/docs/api/java/util/List.html#of-E...-

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/graph/Graph.java
> +    private ArrayList<ArrayList<Integer>> g;
поля обычно принято объявлять в начале класса

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/graph/Graph.java
> +     * @param i first vertex
тут тоже описания методов куда-то пропали, а я вроде бы всё просил заполнять. описания методов нужны, сгенерите джавадок и посмотрите, что получается
-1

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/dijkstra/Dijkstra.java
> +                if (d[j] < mind && !used[j]) {
в условии написано: Среди всех еще не захваченных городов выбирается ближайший __к любому уже захваченному городу__ и захватывается. а у вас тут классический дейкстра, как я понял, который выбирает минимальное расстояние от стартовой вершины. или я не прав?
-1

2018-02-12 07:44 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/dijkstra/Dijkstra.java
> +        double probability = (double) invadors / (double) (invadors + defenders);
а где тут случайность? к тому же имелось в виду, что есть некоторый коэффициент, который влияет на эту формулу, который по условию нужно задавать на входе и который вы в main() замечательно игнорируете. я же специально даже попросил аккуратно всё проверить, ну зачем вы так?
-1

2018-02-12 07:51 UTC, tilacyn commented on Dijkstra/src/main/java/ru/tilacyn/dijkstra/Dijkstra.java
> +                if (d[j] < mind && !used[j]) {
Обычный дейкстра ведь абсолютно корректно решает задачу: нет разницы между понятиями: "ближайший к любому из захваченных" и ближайший к стартовой вершине. Это легко доказать по индукции

2018-02-12 07:55 UTC, tilacyn commented on Dijkstra/src/main/java/ru/tilacyn/dijkstra/Dijkstra.java
> +        double probability = (double) invadors / (double) (invadors + defenders);
Насколько я понял из условия, вероятность выигрыша равна n / (n + m), где n - величина армии захватчиков, а m - величина армии защитников (это написано в документации). То есть эту вероятность и нужно умножать на коэффициент?

Случайность в том, что берется рандомное число от 0 до 1, и вероятность того, что оно меньше probability как раз и равна probability.

Просто из условия про коэффициент кажется, что он не влияет на вероятность, а влияет на размер армий.., то есть пропорции не меняются((

2018-02-13 18:12 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/dijkstra/Dijkstra.java
> +                if (d[j] < mind && !used[j]) {
ок, принимается

2018-02-13 18:20 UTC, jzuken requested changes

2018-02-13 18:20 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/main/Main.java
> +            throw new InputMismatchException("Bad Input\nTry again!\n<input filename> <output filename>\n");
не очень понятно, зачем тут исключение бросать. это же самый верх, тут идёт общение с пользователем. достаточно просто сообщить о проблеме и завершиться

2018-02-13 18:20 UTC, jzuken commented on Dijkstra/src/main/java/ru/tilacyn/main/Main.java
> +        for (int d : dijkstra.getDistances()) {
а где путь до каждого города? :(
`вывести результат всех попыток захвата, номера всех городов в порядке захвата, а также и расстояние и путь от каждого захваченного города до города 1`

2018-02-13 21:43 UTC, tilacyn commented on Dijkstra/src/main/java/ru/tilacyn/main/Main.java
> +        for (int d : dijkstra.getDistances()) {
Ой, я почему-то решил, что пути - это префиксы массива invasionOrder, что, очевидно, не так..

2018-02-14 16:55 UTC, merged