Spiral: requested changes made
tilacyn/practiceJava pull request #7
Opened 2017-10-16 08:50 UTC by tilacyn

Branch br3 contained commits on HashTable and Spiral both so I decided to create a new branch and open a new pull request not to get confused anymore

2017-10-22 14:02 UTC, jzuken requested changes

2017-10-22 14:02 UTC, jzuken commented on Spiral/src/main/java/ru/tilacyn/spiral/Spiral.java
> +        if(n == 1) {
после ключевых слов if, while и т.п. по стайглайду ставятся пробелы: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-142311.html#449
вы бы ознакомились с ним целиком, он не такой большой
-0.5

2017-10-22 14:02 UTC, jzuken commented on Spiral/src/test/java/ru/tilacyn/spiral/SpiralTest.java
> +        assertEquals(12, res[0]);
сурово. но лучше использовать Arrays.equals()

2017-10-22 14:02 UTC, jzuken commented on Spiral/src/test/java/ru/tilacyn/spiral/SpiralTest.java
> +    public void sortByCols() {
одного теста на сортировку маловато будет

2017-11-06 10:50 UTC, jzuken requested changes

2017-11-06 10:50 UTC, jzuken commented on Spiral/src/main/java/ru/tilacyn/spiral/Spiral.java
> +     * @return result matrix
ну так не пойдёт, хоть напишите, что за матрица возвращается. а для аргумента можно указать органичения

2017-11-06 10:50 UTC, jzuken commented on Spiral/src/main/java/ru/tilacyn/spiral/Spiral.java
> +    public static int[][] sortByCols(int arr[][]) {
arr -- фиговое имя для параметра, такой код сразу начинает выглядеть неряшливо

2017-11-06 10:50 UTC, jzuken commented
тут ещё конфликты какие-то с мастером, хорошо бы их поправить

2017-11-08 21:03 UTC, tilacyn commented on Spiral/src/main/java/ru/tilacyn/spiral/Spiral.java
> +    public static int[][] sortByCols(int arr[][]) {
А почему в мастере лежит spiral?

Он по ошибке был помержен?

Просто я не очень понимаю, в чем его смысл и как исправлять конфликты: можно ли его просто удалить из мастера?

2017-11-17 04:45 UTC, jzuken commented on Spiral/src/main/java/ru/tilacyn/spiral/Spiral.java
> +    public static int[][] sortByCols(int arr[][]) {
да, я за мерджил контрольную не глядя, судя по всему, а у вас тут зоопарк с ветками br2 и br4 (который до сих пор не устранён), так что теперь придётся страдать. ничего из мастера удалять отдельными коммитами не надо, иначе потом при мердже других веток будет плохо. по-хорошему надо откатить коммит с мерджем контрольной и заставить вас переделать все ветки нормально, но да ладно. зато научитесь правильно мерджиться и исправлять конфликты

2017-12-03 15:31 UTC, merged