Set
tilacyn/practiceJava pull request #9
Opened 2017-10-18 20:05 UTC by tilacyn

2017-11-05 15:33 UTC, jzuken requested changes

2017-11-05 15:33 UTC, jzuken commented on HashTable/src/main/java/ru/tilacyn/hashTable/HashTable.java
> +package ru.tilacyn.hashTable;
что тут делает хэш-таблица?
Максим, эта ветка должна расти от мастера, в ней не должно быть никаких других задач, кроме множества. я вам уже неоднократно об этом писал, но ничего не меняется, вы продолжаете делать новые ветки друг от друга. если у вас сложности при работе с гитом, подойдите на занятии, я вам покажу, чего я от вас хочу, и как этого добиться
-1

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +package ru.tilacyn.set;
к сожалению, опять отсутствует система сборки. пора бы уже начать какой-либо из них пользоваться, полсеместра уже прошло
-1

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> + * @param <T>
параметр-тип класса тоже нужно документировать

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +
пустые строки между комментами и комментируемой сущностью обычно не ставят

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +        public T value;
даже у приватных вложенных классов лучше не использовать публичные поля

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +    /**
этот комментарий имеет смысл оформить в одну строку: /** ... */

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +    private boolean leq(T first, T second) {
неудачное имя функции, непонятное

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +     * @param value
а тут где комментарий? 
-1 за доки

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +        boolean lastDir = false;
lastDir логического типа. и что бы оно значило?

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +    public boolean contains(T value) {
пробела не хватает

2017-11-05 15:33 UTC, jzuken commented on Set/src/main/java/ru/tilacyn/set/Set.java
> +            tree = new Node<T>(value);
тут можно Т не указывать, оно само выведет

2017-11-05 15:33 UTC, jzuken commented on Set/src/test/java/ru/tilacyn/set/SetTest.java
> +        assert setInt.add(1);
этот ассерт прекратит работу программы, если не выполнится условие. вы точно такого поведения хотите?

2017-11-05 17:37 UTC, tilacyn commented on HashTable/src/main/java/ru/tilacyn/hashTable/HashTable.java
> +package ru.tilacyn.hashTable;
А, в смысле надо делать git branch из мастера? Я почему-то не понимал, что есть такая проблема..

2017-11-06 07:50 UTC, jzuken commented on HashTable/src/main/java/ru/tilacyn/hashTable/HashTable.java
> +package ru.tilacyn.hashTable;
вот и у меня вопрос, почему. я в каждой задаче про это пишу:
https://github.com/tilacyn/practiceJava/pull/3#issuecomment-338479084
https://github.com/tilacyn/practiceJava/pull/6#discussion_r146129865

2017-11-26 22:52 UTC, tilacyn commented on Set/src/test/java/ru/tilacyn/set/SetTest.java
> +        assert setInt.add(1);
Можете объяснить, в чем проблема? Не очень понял, это же SetTest

2017-11-27 11:17 UTC, jzuken commented on Set/src/test/java/ru/tilacyn/set/SetTest.java
> +        assert setInt.add(1);
проблема в том, что в релизной сборке этой строчки вообще не будет. мне кажется, вы перепутали assert и assertTrue, нет?

2017-12-05 13:40 UTC, closed without merging